### ISSUE TITLE
How can I run this project?

### ISSUE THREAD

**Issue by springheart199279** [springheart199279/my-vue#1]
Now this project is not working.
Please help me.

const msalConfig = {
  auth: {
    clientId: 'ENTER_YOUR_CLIENT_ID_HERE',
    authority: 'https://login.microsoftonline.com/ENTER_YOUR_TENANT_ID_HERE',
    redirectUri: '/', // Must be registered as a SPA redirectURI on your app registration
    postLogoutRedirectUri: '/' // Must be registered as a SPA redirectURI on your app registrationregistration
  },
  cache: {
    cacheLocation: 'localStorage' // Options are localStorage, sessionStorage, memoryStorage
  },
};

export const msalInstance = new PublicClientApplication(msalConfig);

**Comment by aidear3** [comment]
1. npm install
2. npm start

Please check clientId more carefully.

**Comment by springheart199279** [comment]
Thanks.
